"""
Service Layer Package.

Provides a clean, decoupled application boundary between core audited domain engines
(valuation, normalization, filing intelligence, research) and future presentation interfaces (Streamlit UI).
"""
from src.service.contracts import (
    AnalysisResponse,
    CompanyProfile,
    CompanyRequest,
    FilingIntelligenceResponse,
    FilingSignal,
    InvalidRequestError,
    InvalidTickerError,
    MissingCompanyError,
    MissingPITDateError,
    PlatformServiceError,
    ResearchDisclosure,
    UnsupportedModeError,
    ValuationRequest,
    ValuationResponse,
    ValuationUnavailableError,
    FinancialPeriodDTO,
    FinancialFeatureDTO,
    FundamentalsResponse,
    FilingSectionDTO,
    FilingSummaryDTO,
    FilingExplorerResponse,
    ValuationBridgeRecordDTO,
    SourceProvenanceDTO,
    LineageStepDTO,
    DataLineageDTO,
    QualitativeEvidenceLineageDTO,
    ValuationBridgeLineageDTO,
    FundamentalChangeDTO,
    WhatChangedResponse,
)
from src.service.platform_service import PlatformService

__all__ = [
    "PlatformService",
    "CompanyRequest",
    "CompanyProfile",
    "ValuationRequest",
    "ValuationResponse",
    "FilingSignal",
    "FilingIntelligenceResponse",
    "ResearchDisclosure",
    "AnalysisResponse",
    "PlatformServiceError",
    "InvalidRequestError",
    "InvalidTickerError",
    "UnsupportedModeError",
    "MissingPITDateError",
    "MissingCompanyError",
    "ValuationUnavailableError",
    "FinancialPeriodDTO",
    "FinancialFeatureDTO",
    "FundamentalsResponse",
    "FilingSectionDTO",
    "FilingSummaryDTO",
    "FilingExplorerResponse",
    "ValuationBridgeRecordDTO",
    "SourceProvenanceDTO",
    "LineageStepDTO",
    "DataLineageDTO",
    "QualitativeEvidenceLineageDTO",
    "ValuationBridgeLineageDTO",
    "FundamentalChangeDTO",
    "WhatChangedResponse",
]
